version: '3.4'

services:
  app:
    build: # NOTE: unusually using ./ as build context so we can use .git info in gradle
      context: ./
      dockerfile: app/Dockerfile
      args:
        BUILDER_BASE: gradle:5.0.0-jdk11-slim
        DOCKER_BASE: openjdk:12-ea-25-jdk-alpine3.8
        VCS_REF: ${VCS_REF:-git_commit}
        BUILD_DATE: ${BUILD_DATE:-build_date}
        DOCKER_TAG: ${DOCKER_TAG:-0.1.0}
    ports: ['8080:8080']
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
